### PR TITLE
Refactor redux actions

### PR DESCRIPTION
**Pull request by notwaldorf**
Moved the offline/location callbacks to redux-land. This doesn't work right now because i am getting the "you are now online" toast on first load and I don't know why 😭 

I don't thiiiiink there's any reselects I need to use, but I also only half understand reselects.

### CODE REVIEW

**Comment by frankiefu** [comment]
For the online toast appears on first load, I suspect it's because the app state is stored in localstorage so when you load the app it will just get `app.offline=false` initially.

**Comment by notwaldorf** [comment]
ohhh you are correct

**Comment by frankiefu** [comment]
One candidate for `reselect` is this [code](https://github.com/notwaldorf/flash-cards/blob/22a2847ef9d7c1e5301a8e70647bc7509d72540e/src/components/play-page.js#L151-L173) that basically transform state data to `this._card`. The selector would look something like this:
```js
const cardsSelector =  state => state.data.cards;
const activeCardSelector =  state => state.data.activeCard;

export const cardSelector = createSelector(
  cardsSelector,
  activeCardSelector,
  (cards, activeCard) => {

    ...
    
    return {
      question: activeCardData.jp,
      answers: answers,
      category: activeCard.category,
      mnemonic: activeCardData.mnemonic
    }
  }
);
```
And in `play-page.js`:
```js
_stateChanged(state) {
  ...
  this._card = cardSelector(state);
}
```
One advantage of using reselect is it will recalculate `this._card` only when the value of `state.data.cards` or `state.data.activeCard` changes.

**Comment by frankiefu** [comment]
💯

**Pull request merged**
