### PR TITLE
fix for firefox

### PR DESCRIPTION
**Pull request by frankiefu**
Was trying out the https://flash-cards.netlify.com in Firefox and noticed settings and stats are not being saved.
- need to set `bubbles: true` because the event needs to bubbles up through the DOM in Shady DOM
- update dependencies

### CODE REVIEW

**Comment by notwaldorf** [comment]
Thanks! Weird it worked everywhere else 😳

**Comment by notwaldorf** [comment]
(the tests are known bad)

Hmm, the deploy throws this error. Have we seen this before?
screen shot 2018-05-09 at 7 54 48 am

**Comment by frankiefu** [comment]
The build presets were out of date. Just [updated](https://github.com/notwaldorf/flash-cards/pull/10/commits/17532f8e862862dbd9c4a4a4e89f6d510344abb1) and should be good now.

**Comment by notwaldorf** [comment]
hmm it seems to have the same error. let me try locally.

**Pull request merged**
